// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk_F4__KL3F0e7jsjAAshmRD4nHYq3XLE',
    appId: '1:379081659194:web:40bd49e4525bc11dc53603',
    messagingSenderId: '379081659194',
    projectId: 'todo-app-9ee94',
    authDomain: 'todo-app-9ee94.firebaseapp.com',
    storageBucket: 'todo-app-9ee94.appspot.com',
    measurementId: 'G-T1C7WM4HWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdwuOX0-6mC-TgWwvefB24hamaFpG-lyQ',
    appId: '1:379081659194:android:49d652face769dd4c53603',
    messagingSenderId: '379081659194',
    projectId: 'todo-app-9ee94',
    storageBucket: 'todo-app-9ee94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDWHgCpigfkyAcaTe_xCUvPBeDCy4m8Hg',
    appId: '1:379081659194:ios:df7ebf1f8fd0343bc53603',
    messagingSenderId: '379081659194',
    projectId: 'todo-app-9ee94',
    storageBucket: 'todo-app-9ee94.appspot.com',
    iosClientId: '379081659194-36antbff5a9hmemfccc6hl6hi8laabmg.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDWHgCpigfkyAcaTe_xCUvPBeDCy4m8Hg',
    appId: '1:379081659194:ios:df7ebf1f8fd0343bc53603',
    messagingSenderId: '379081659194',
    projectId: 'todo-app-9ee94',
    storageBucket: 'todo-app-9ee94.appspot.com',
    iosClientId: '379081659194-36antbff5a9hmemfccc6hl6hi8laabmg.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
